### ISSUE TITLE
unable to reproduce the results with the provided  the model and the specified environment. 

### ISSUE THREAD

**Issue by kailigo** [MengyuanChen21/ECCV2022-DELU#1]
Hi Authors,

I run the test code with the provided weights and get,

map @ 0.1 = 69.233 ||map @ 0.2 = 63.999 ||map @ 0.3 = 54.663 ||map @ 0.4 = 46.056 ||map @ 0.5 = 38.931 ||map @ 0.6 = 26.078 ||map @ 0.7 = 14.830 ||map @ 0.8 = 7.587 ||map @ 0.9 = 1.919

mAP Avg ALL: 35.922
mAP Avg 0.1-0.5: 54.57627638559677, mAP Avg 0.1-0.7: 44.82698976554239, mAP Avg ALL: 35.921653422704104

which are lower than the reported one in the paper.

I have the same configuration for the environment as the suggested. Thanks.

**Comment by MengyuanChen21** [comment]
Hello Kailigo,

Thank you for reaching out! Sorry for the late reply. I have just seen the issue.

I have just downloaded the codes and the pre-trained model, and then rerun the test script with nothing changed. Below is the screenshot I obtained 5 minutes ago, whose result is exactly the same with the reported one in the paper.

I do not think this issue is related to randomness or environment configuration since it is only a test process. However, it may be helpful to create a clean environment and re-download the codes and the checkpoint model.

Please contact me if you have any further problem. I hope everyone can reproduce my work.

<img width="1121" alt="test_result" src="https://user-images.githubusercontent.com/102446521/208332331-2e4a0a5c-57d9-4e3e-9690-2cbb32ce76e6.png">
