### ISSUE TITLE
重新训练没办法复现论文报告的结果

### ISSUE THREAD

**Issue by huangjinghuangjing** [MengyuanChen21/ECCV2022-DELU#2]
作者您好，感谢您非常精彩的工作。但是，本人使用您提供的代码进行训练，训不出您在论文里报告的结果（thumos的map在45.4左右），是有什么需要注意的细节吗？

**Comment by MengyuanChen21** [comment]
Thank you for your attention to our work. We have re-tested the model we released, whose results are shown below.
<img width="1121" alt="test" src="https://user-images.githubusercontent.com/102446521/208658658-4d7c2c21-2edb-41da-9be6-170be1c09d99.png">

When we train the model again, the results are also the same.
<img width="1327" alt="train" src="https://user-images.githubusercontent.com/102446521/208658664-b012c31f-7cfe-4685-88f4-6a5ac978ab35.png">

We will further re-check the released codes. But we think it may be caused by the environment. Moreover, we use 3090RTX and our Linux system is shown below.
<img width="1151" alt="linux" src="https://user-images.githubusercontent.com/102446521/208658669-03f96fea-7e42-4845-8b0c-c9752af09508.png">

Some advice for repeating our results:
1. Create the same anaconda environment as described in our README file. The ‘requirement.txt’ file may be helpful.
2. Run the testing commands in ‘test.sh’, which you can get the results as we showed.
3. Run the training commands. It may be influenced by the environment. Different environments may introduce different seeds, which further influence the training order, leading to different results.
