### ISSUE TITLE
Multi gpu operation

### ISSUE THREAD

**Issue by eeehco** [MengyuanChen21/ECCV2022-DELU#7]
Hello, author. I would like to ask if the code for DELU can only be run through a single gpu？

**Comment by MengyuanChen21** [comment]
I haven't experimented with multiple GPUs yet. All the existing experiments are carried out on a single RTX 3090 GPU. In theory, the DELU code could be adapted to run on multiple GPUs, but I'm not sure how that would affect performance.

Since the scale of the Act-v1.2 dataset (4800 videos) is much larger than THUMOS14 (200 videos), the training time on Act-v1.2 is also much longer. A small tip is that reducing the test frequency before the model converges can slightly reduce the training time required.

**Comment by eeehco** [comment]
Okay, I see. Thank you
